### ISSUE TITLE
Enable Users to update an analysis' status to Ready or Active 

### ISSUE THREAD

**Issue by SeriousHorncat** [uab-cgds-worthey/rosalution#53]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] Check that there isn't [already an proposed enhancement](https://github.com/uab-cgds-worthey/rosalution/issues/) that accomplishes the same thing.
- [X] Follow our [Code of Conduct](https://github.com/uab-cgds-worthey/rosalution/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/uab-cgds-worthey/rosalution/blob/main/CONTRIBUTING.md).

### Description

As a user, I need to update an analysis' status that is either Ready or Active so that collaborators know when cases are ready for review or begun an active review.

### Suggested solution

There is an action drop menu available  in the top right of the header within the a Rosalution analysis to add these two actions.

<img width="186" alt="Screen Shot 2023-03-07 at 2 18 52 PM" src="https://user-images.githubusercontent.com/1209059/223542808-3e2d4924-cfa4-4b68-85f3-a40f8edc5a4e.png">

* Menu actions for the Analysis View are stored in `./frontend/src/views/AnalysisView.vue` in the data value **menuActions**
* The icons used to represent "Mark Ready"  is  'clipboard-check' and "Mark Active" is 'book-open.' The **Mark Active* action, should contain the  divider: true instead of the "Edit" action now.
* There will need to be new Analysis model methods in `./frontend/src/models/analyses.js`  to call the API endpoints that exist to update an analysis' status. See the api/docs when Rosalution is deployed to find these endpoints to use
* These new methods added  the model can be used in new methods within the view to call the API.  A prompt ought to be provided to the user that the operation was a success. The existing 'notificationDialog' within that view can be used for this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jbarkley256** [comment]
I would like to pick up this task.

**Comment by jbarkley256** [comment]
What is the preferred action when an analysis is already marked as ready/completed/active?

**Comment by SeriousHorncat** [comment]
I brought this up with the other maintainers.  We only show the available actions according to the analysis '**latest_status**'.  
So in this case, that means

**latest_status -> available actions**  
Annotating -> Mark Ready
Ready -> Mark Active
