### ISSUE TITLE
HTTPS setup for local development deployments

### ISSUE THREAD

**Issue by SeriousHorncat** [uab-cgds-worthey/rosalution#72]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] Check that there isn't [already an proposed enhancement](https://github.com/uab-cgds-worthey/rosalution/issues/) that accomplishes the same thing.
- [X] Follow our [Code of Conduct](https://github.com/uab-cgds-worthey/rosalution/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/uab-cgds-worthey/rosalution/blob/main/CONTRIBUTING.md).

### Description

As a developer, I need the local development deployment to utilize HTTPS so that it can behave as much as possible like our production deployments.

### Suggested solution

This will require updates to the local Traefik configuration and the backend options.

Some article references on how to approach.

- https://towardsdatascience.com/how-to-deploy-a-secure-api-with-fastapi-docker-and-traefik-b1ca065b100f
- Great tutorial and resource for FastAPI and setting up TLS (Transport Layer Security) for HTTPS with certificates using LetsEncrypt.
  - https://fastapi.tiangolo.com/deployment/docker/#behind-a-tls-termination-proxy
  - Will need to update the TLS Termination Proxy with the '--proxy-headers' to the uvicorn executable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sazanaizu33** [comment]
I'd like to take this one.
